# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
import os
from selenium.webdriver.support import expected_conditions as EC
INPUT_PATH = os.path.join(os.path.dirname(__file__), "Input_calendar_file_test.json")
def get_authen_info():
  with open(INPUT_PATH, 'r') as f:
    combined_data = json.load(f)
  # Lấy dữ liệu authen
  authen_data = combined_data.get('authen', [])  # Dùng get để tránh lỗi nếu key không tồn tại
  return authen_data
def get_test_data():
  with open(INPUT_PATH, 'r') as f:
    combined_data = json.load(f)
  test_url_data = combined_data.get('file_data', [])
  # Lấy dữ liệu test
  return [(d["name"], d["file"], d["expected"]) for d in test_url_data]
class TestTC001012():
  def setup_method(self, method):
    options = webdriver.ChromeOptions()
    options.add_argument('--no-sandbox')
    options.add_argument('--disable-dev-shm-usage')
    options.add_argument("--inprivate")
    self.driver = webdriver.Chrome(options=options)
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def precondition(self):
    authen_data = get_authen_info()
    self.driver.delete_all_cookies()
    # Mở trang đăng nhập
    self.driver.get("https://sandbox.moodledemo.net/calendar/import.php?")
    time.sleep(1)
    # Nhập thông tin đăng nhập
    username = authen_data[0].get('username')  # Thay bằng tài khoản thật
    password = authen_data[0].get('password')  # Thay bằng mật khẩu thật
    
    # Tìm trường nhập username/password và nút đăng nhập
    self.driver.find_element(By.ID, "username").send_keys(username)  # ID của trường username
    self.driver.find_element(By.ID, "password").send_keys(password)  # ID của trường password
    self.driver.find_element(By.ID, "loginbtn").click()  # ID của nút đăng nhập
  def log_out(self):
    self.driver.get("https://sandbox.moodledemo.net/")
    self.driver.find_element(By.ID, "user-menu-toggle").click()
    time.sleep(1)
    self.driver.find_element(By.LINK_TEXT, "Log out").click()
    time.sleep(5)
  @pytest.mark.parametrize("name, file, expected", get_test_data())
  def test_tC001012(self, name, file, expected):
    self.precondition()
    #self.driver.get("https://sandbox.moodledemo.net/calendar/import.php?")
    self.driver.find_element(By.ID, "id_name").click()
    self.driver.find_element(By.ID, "id_name").send_keys(name)
    self.driver.find_element(By.ID, "id_importfrom").click()
    dropdown = self.driver.find_element(By.ID, "id_importfrom")
    dropdown.find_element(By.XPATH, "//option[. = 'Calendar file (.ics)']").click()
    file_name = os.path.basename(file)
    if (file != ""):
      time.sleep(5)
      upload_button = WebDriverWait(self.driver, 10).until(
        EC.element_to_be_clickable((By.NAME, "importfilechoose"))
      )
      upload_button.click()
      upload_button = WebDriverWait(self.driver, 10).until(
        EC.element_to_be_clickable((By.XPATH, "/html/body/div[6]/div[3]/div/div[2]/div/div/div[1]/div[3]/a/span"))
        
      )
      upload_button.click()
      # self.driver.find_element(By.XPATH, "/html/body/div[6]/div[3]/div/div[2]/div/div/div[1]/div[3]/a/span").click()
      
      # Chờ phần tử hiển thị và khả dụng
      upload_button = WebDriverWait(self.driver, 10).until(
        EC.element_to_be_clickable((By.NAME, "repo_upload_file"))
      )
      time.sleep(3)
      self.driver.find_element(By.XPATH, "//input[@type=\'file\']").send_keys(file)
      
      # Chờ cho đến khi nút có thể được click
      upload_button = WebDriverWait(self.driver, 10).until(
          EC.element_to_be_clickable((By.XPATH, "//div[2]/div/div[2]/div/div/div/button"))
      )
      # Sau khi đảm bảo nó đã sẵn sàng, click vào nút
      upload_button.click()
      if expected == "Text file filetype cannot be accepted.":
        print("File type cannot be accepted")
        WebDriverWait(self.driver, 5).until(
          EC.visibility_of_element_located((By.XPATH, "//div[normalize-space()='Text file filetype cannot be accepted.']"))
        )
        assert True
        self.log_out()
        return  # Kết thúc kiểm thử khi lỗi xuất hiện
      elif expected == f"""The file \'{file_name}\' is either empty or a folder. To upload folders zip them first.""":
        print(f"The file '{file_name}' is either empty or a folder")
        WebDriverWait(self.driver, 5).until(
          EC.visibility_of_element_located((By.XPATH, f"//div[contains(text(), \"{expected}\")]"))
        )
        assert True
        self.log_out()
        return  # Kết thúc kiểm thử khi lỗi xuất hiện
    self.driver.find_element(By.ID, "id_add").click()
    time.sleep(3)
    if expected == "- Required":
      assert self.driver.find_element(By.XPATH, "//*[@id=\"id_error_name\"]").text == expected
    elif expected == "Either a URL or a file is required to import a calendar.":
      assert self.driver.find_element(By.XPATH, "//*[@id=\"id_error_importfile\"]").text == expected
    else:
      assert self.driver.find_element(By.XPATH, "//*[@id=\"region-main\"]/div/h2").text == expected
    self.log_out()
        
  
